### ISSUE TITLE
small-desktop-unit-** different from npm package

### ISSUE THREAD

**Issue by ianmiller347** [thatgibbyguy/ply#34]
File: `src/scss/components/_grid.scss`

For small-desktop breakpoints, in the github repo, `@media (min-width: $breakpoint-small-desktop) {` is used, but in the npm package, `max-width` is used.

This causes an issue where, for example, any cell using both `small-desktop-unit-**` and `large-phone-unit-**` always takes the small-desktop number, regardless of screen size.

Proposed fix: update npm package with latest code in github repo.

**Comment by thatgibbyguy** [comment]
To clarify, the issue is when pairing classes together such as `small-desktop-unit-xx large-phone-desktop-unit-xx` the small desktop unit may override the large phone unit styling.

Will look into it.

**Comment by Dannyalmighty** [comment]
<div class="unit-33 small-desktop-unit-50 large-phone-unit-100 ">
Is the example i'm trying to use.  On phones, the view sticks to the unit-50 properties instead of unit-100.

**Comment by Dannyalmighty** [comment]
`<div class="analytics-container unit-33 small-desktop-unit-50 large-phone-unit-100">`

**Comment by ianmiller347** [comment]
The issue with large-phone overriding small-desktop is a non-issue, but the npm package still needs to be synchronized with the github repo. This issue can be closed after that.

**Comment by thatgibbyguy** [comment]
fixed and closed
