### ISSUE TITLE
.btn should allow simple margin overrides

### ISSUE THREAD

**Issue by ianmiller347** [thatgibbyguy/ply#38]
Developing with helper classes has become an excellent use of ply.

Simply pulling and using ply iso or complete, one should be able to simply use something like the following:

`<button class="btn margins--margin-bottom">ClickyBoy</button>`

To show a button with some margin below it to leave some breathing room before the next bit of content starts. 

However, The `.btn` has a `margin: 0` which overrides this simple helper class.

Proposed solutions: 
1. Remove `margin: 0` from the `.btn` selector.
2. Remove the `button.btn` selector
3. Only use button, input[type="button"], etc selectors for bg, border, radius, and not for margin: 0 
4. Some kind of combination of the above.

Thoughts?

**Comment by thatgibbyguy** [comment]
Stale, if it needs more discussion reopen it.
